"""Write-time gate for AI-written node configs.

Pins the 2026-07-16 trial-killing bug class: the agentic builder wrote an
approval node's `fields` as a stringified JSON object; validation was
advisory-only, the value persisted, and every run died at the runtime parse
with "config.fields: Input should be a valid list".

The gate has three layers, all covered here:
  1. coerce_config_value_types — deterministically parses stringified-JSON
     container values (and wraps a lone object where the model wants a list).
  2. config_value_errors — reports wrong-typed PRESENT values only (top-level
     missing-required is normal mid-build and excluded).
  3. strip_label_sidecars — drops __label display-cache keys from AI writes
     (a stale/wrong sidecar renders the wrong label and blocks FE self-heal).
"""

import json

from coder.workflow.operation_catalog import (
    coerce_config_value_types,
    config_value_errors,
    reject_invalid_config_values,
)
from coder.workflow.workflow_ops import strip_label_sidecars


# The exact shape the builder wrote in the incident (stringified single object
# in a List[ApprovalField] field, template inside).
STRINGIFIED_FIELDS_JSON = json.dumps({
    "name": "response",
    "type": "string",
    "label": "Agent Response",
    "description": "The response generated by the agent",
    "required": False,
    "value": "{{ $('agent').response }}",
})


class TestConfigValueErrors:
    def test_stringified_list_field_is_reported(self):
        errors = config_value_errors(
            "approval", "default", {"title": "Review", "fields": STRINGIFIED_FIELDS_JSON}
        )
        assert any(key == "fields" for key, _ in errors)

    def test_top_level_missing_required_is_not_reported(self):
        # Incremental building: an incomplete config is not a value error.
        errors = config_value_errors("approval", "default", {"title": "Review"})
        assert errors == []

    def test_nested_missing_inside_provided_container_is_reported(self):
        # A provided list whose item is malformed IS a value error.
        errors = config_value_errors(
            "approval", "default",
            {"title": "Review", "fields": [{"label": "no name key"}]},
        )
        assert errors, "malformed item inside a provided container must be reported"

    def test_valid_config_reports_nothing(self):
        errors = config_value_errors(
            "approval", "default",
            {"title": "Review", "fields": [{"name": "response", "type": "string"}]},
        )
        assert errors == []

    def test_domain_errors_are_not_reported(self):
        # The agent's model_type discriminator carries values the resolved
        # operation class doesn't know ('image'); a literal/enum mismatch is
        # NOT proof the value is wrong and must never be enforced/reverted
        # (regression: test_batch_setting_both_keeps_explicit_discriminator).
        errors = config_value_errors(
            "agent", "default",
            {"model": "openrouter/google/gemini-2.5-flash-image", "model_type": "image"},
        )
        assert errors == []


class TestCoercion:
    def test_stringified_fields_json_coerces_to_list(self):
        config = {"title": "Review", "fields": STRINGIFIED_FIELDS_JSON}
        notes = coerce_config_value_types("approval", "default", config)
        assert notes, "coercion should have fired"
        assert isinstance(config["fields"], list)
        assert config["fields"][0]["name"] == "response"
        assert config_value_errors("approval", "default", config) == []

    def test_stringified_array_coerces(self):
        config = {
            "title": "Review",
            "fields": json.dumps([{"name": "a", "type": "string"}]),
        }
        notes = coerce_config_value_types("approval", "default", config)
        assert notes
        assert isinstance(config["fields"], list)

    def test_unparseable_string_left_alone(self):
        config = {"title": "Review", "fields": "{not json"}
        notes = coerce_config_value_types("approval", "default", config)
        assert notes == []
        assert config["fields"] == "{not json"


class TestRejectInvalidConfigValues:
    def test_coercible_value_is_fixed_not_rejected(self):
        config = {"title": "Review", "fields": STRINGIFIED_FIELDS_JSON}
        notes, rejected = reject_invalid_config_values(
            "approval", "default", config, {"fields", "title"}
        )
        assert notes
        assert rejected == []
        assert isinstance(config["fields"], list)

    def test_uncoercible_changed_key_is_rejected(self):
        config = {"title": "Review", "fields": "just some prose"}
        notes, rejected = reject_invalid_config_values(
            "approval", "default", config, {"fields"}
        )
        assert any(key == "fields" for key, _ in rejected)

    def test_unchanged_bad_key_is_not_rejected(self):
        # Pre-existing damage isn't this write's fault — advisory only.
        config = {"title": "Review", "fields": "just some prose"}
        _, rejected = reject_invalid_config_values(
            "approval", "default", config, {"title"}
        )
        assert rejected == []

    def test_template_string_is_exempt(self):
        config = {"title": "Review", "fields": "{{ $('agent').fields }}"}
        _, rejected = reject_invalid_config_values(
            "approval", "default", config, {"fields"}
        )
        assert rejected == []


class TestStripLabelSidecars:
    def test_drops_all_sidecars(self):
        config = {
            "hermes_agent_model": "openrouter/tencent/hy3:free",
            "hermes_agent_model__label": "[OpenRouter] OpenAI GPT Mini Latest - 400K ctx",
            "model": "hermes",
            "model__label": "hermes",
        }
        dropped = strip_label_sidecars(config)
        assert set(dropped) == {"hermes_agent_model__label", "model__label"}
        assert "hermes_agent_model__label" not in config
        assert config["hermes_agent_model"] == "openrouter/tencent/hy3:free"

    def test_changed_keys_variant_is_idempotent(self):
        config = {"model": "x", "model__label": "stale"}
        strip_label_sidecars(config, changed_keys={"model"})
        assert config == {"model": "x"}
        # second call is a no-op
        assert strip_label_sidecars(config, changed_keys={"model"}) == []
