# OAuth utilities for workflow nodes.
# Provides OAuth 2.0 token management for various providers (Google, Airtable, GitHub, Linear, Notion, Reddit, Microsoft, Facebook, Twitter, Slack, WordPress).

from nodes.oauth.google_oauth import (
    GoogleTokens,
    GoogleUserInfo,
    get_google_client_config,
    exchange_code_for_tokens as google_exchange_code_for_tokens,
    refresh_access_token as google_refresh_access_token,
    validate_token as google_validate_token,
    is_token_expired as google_is_token_expired,
    get_google_auth_url,
    revoke_token as google_revoke_token,
)

from nodes.oauth.airtable_oauth import (
    AirtableTokens,
    AirtableUserInfo,
    get_airtable_client_config,
    generate_pkce_verifier,
    generate_pkce_challenge,
    exchange_code_for_tokens as airtable_exchange_code_for_tokens,
    refresh_access_token as airtable_refresh_access_token,
    is_token_expired as airtable_is_token_expired,
    get_airtable_auth_url,
    AIRTABLE_FULL_SCOPES,
)

from nodes.oauth.github_oauth import (
    GithubTokens,
    GithubUserInfo,
    get_github_client_config,
    exchange_code_for_tokens as github_exchange_code_for_tokens,
    refresh_access_token as github_refresh_access_token,
    is_token_expired as github_is_token_expired,
    get_github_auth_url,
    GITHUB_WORKFLOW_SCOPES,
    GITHUB_PUBLIC_SCOPES,
)

from nodes.oauth.atlassian_oauth import (
    AtlassianTokens,
    AtlassianResource,
    AtlassianUserInfo,
    get_atlassian_client_config,
    exchange_code_for_tokens as atlassian_exchange_code_for_tokens,
    refresh_access_token as atlassian_refresh_access_token,
    is_token_expired as atlassian_is_token_expired,
    get_atlassian_auth_url,
    JIRA_WORKFLOW_SCOPES,
    JIRA_READ_ONLY_SCOPES,
)

from nodes.oauth.linear_oauth import (
    LinearTokens,
    LinearUserInfo,
    get_linear_client_config,
    exchange_code_for_tokens as linear_exchange_code_for_tokens,
    refresh_access_token as linear_refresh_access_token,
    is_token_expired as linear_is_token_expired,
    get_linear_auth_url,
    revoke_token as linear_revoke_token,
    LINEAR_DEFAULT_SCOPES,
)

from nodes.oauth.gitlab_oauth import (
    GitLabTokens,
    GitLabUserInfo,
    get_gitlab_client_config,
    exchange_code_for_tokens as gitlab_exchange_code_for_tokens,
    refresh_access_token as gitlab_refresh_access_token,
    is_token_expired as gitlab_is_token_expired,
    get_gitlab_auth_url,
    GITLAB_DEFAULT_SCOPES,
)
from nodes.oauth.box_oauth import (
    BoxTokens,
    BoxUserInfo,
    get_box_client_config,
    exchange_code_for_tokens as box_exchange_code_for_tokens,
    refresh_access_token as box_refresh_access_token,
    is_token_expired as box_is_token_expired,
    get_box_auth_url,
    BOX_DEFAULT_SCOPES,
)

from nodes.oauth.clickup_oauth import (
    ClickUpTokens,
    ClickUpUserInfo,
    get_clickup_client_config,
    exchange_code_for_tokens as clickup_exchange_code_for_tokens,
    refresh_access_token as clickup_refresh_access_token,
    is_token_expired as clickup_is_token_expired,
    get_clickup_auth_url,
    CLICKUP_DEFAULT_SCOPES,
)
from nodes.oauth.asana_oauth import (
    AsanaTokens,
    AsanaUserInfo,
    get_asana_client_config,
    exchange_code_for_tokens as asana_exchange_code_for_tokens,
    refresh_access_token as asana_refresh_access_token,
    is_token_expired as asana_is_token_expired,
    get_asana_auth_url,
    ASANA_DEFAULT_SCOPES,
)
from nodes.oauth.monday_oauth import (
    MondayTokens,
    MondayUserInfo,
    get_monday_client_config,
    exchange_code_for_tokens as monday_exchange_code_for_tokens,
    refresh_access_token as monday_refresh_access_token,
    is_token_expired as monday_is_token_expired,
    get_monday_auth_url,
    MONDAY_DEFAULT_SCOPES,
)

from nodes.oauth.reddit_oauth import (
    RedditTokens,
    RedditUserInfo,
    get_reddit_client_config,
    exchange_code_for_tokens as reddit_exchange_code_for_tokens,
    refresh_access_token as reddit_refresh_access_token,
    is_token_expired as reddit_is_token_expired,
    get_reddit_auth_url,
    REDDIT_WORKFLOW_SCOPES,
)

from nodes.oauth.notion_oauth import (
    NotionTokens,
    NotionWorkspaceInfo,
    get_notion_client_config,
    exchange_code_for_tokens as notion_exchange_code_for_tokens,
    refresh_access_token as notion_refresh_access_token,
    is_token_expired as notion_is_token_expired,
    get_notion_auth_url,
)

from nodes.oauth.microsoft_oauth import (
    MicrosoftTokens,
    MicrosoftUserInfo,
    get_microsoft_client_config,
    exchange_code_for_tokens as microsoft_exchange_code_for_tokens,
    refresh_access_token as microsoft_refresh_access_token,
    validate_token as microsoft_validate_token,
    is_token_expired as microsoft_is_token_expired,
    get_microsoft_auth_url,
    revoke_token as microsoft_revoke_token,
)

from nodes.oauth.facebook_oauth import (
    FacebookTokens,
    InstagramAccountInfo,
    get_facebook_client_config,
    exchange_code_for_tokens as facebook_exchange_code_for_tokens,
    refresh_access_token as facebook_refresh_access_token,
    validate_token as facebook_validate_token,
    is_token_expired as facebook_is_token_expired,
    get_facebook_auth_url,
)

from nodes.oauth.twitter_oauth import (
    TwitterTokenResponse,
    TwitterUserInfo,
    exchange_code_for_tokens as twitter_exchange_code_for_tokens,
    refresh_access_token as twitter_refresh_access_token,
    is_token_expired as twitter_is_token_expired,
    get_user_info as twitter_get_user_info,
    revoke_token as twitter_revoke_token,
    calculate_expires_at as twitter_calculate_expires_at,
)

from nodes.oauth.slack_oauth import (
    SlackTokens,
    SlackWorkspaceInfo,
    get_slack_client_config,
    exchange_code_for_tokens as slack_exchange_code_for_tokens,
    refresh_access_token as slack_refresh_access_token,
    is_token_expired as slack_is_token_expired,
    get_slack_auth_url,
    validate_token as slack_validate_token,
    SLACK_WORKFLOW_SCOPES,
    SLACK_READONLY_SCOPES,
)

from nodes.oauth.typeform_oauth import (
    TypeformTokens,
    TypeformUserInfo,
    get_typeform_client_config,
    exchange_code_for_tokens as typeform_exchange_code_for_tokens,
    refresh_access_token as typeform_refresh_access_token,
    is_token_expired as typeform_is_token_expired,
    get_typeform_auth_url,
    TYPEFORM_FULL_SCOPES,
)

from nodes.oauth.wordpress_oauth import (
    WordPressTokens,
    WordPressUserInfo,
    get_wordpress_client_config,
    exchange_code_for_tokens as wordpress_exchange_code_for_tokens,
    refresh_access_token as wordpress_refresh_access_token,
    is_token_expired as wordpress_is_token_expired,
    get_wordpress_auth_url,
    WORDPRESS_DEFAULT_SCOPES,
)

__all__ = [
    # Google
    "GoogleTokens",
    "GoogleUserInfo",
    "get_google_client_config",
    "google_exchange_code_for_tokens",
    "google_refresh_access_token",
    "google_validate_token",
    "google_is_token_expired",
    "get_google_auth_url",
    "google_revoke_token",
    # Airtable
    "AirtableTokens",
    "AirtableUserInfo",
    "get_airtable_client_config",
    "generate_pkce_verifier",
    "generate_pkce_challenge",
    "airtable_exchange_code_for_tokens",
    "airtable_refresh_access_token",
    "airtable_is_token_expired",
    "get_airtable_auth_url",
    "AIRTABLE_FULL_SCOPES",
    # GitHub
    "GithubTokens",
    "GithubUserInfo",
    "get_github_client_config",
    "github_exchange_code_for_tokens",
    "github_refresh_access_token",
    "github_is_token_expired",
    "get_github_auth_url",
    "GITHUB_WORKFLOW_SCOPES",
    "GITHUB_PUBLIC_SCOPES",
    # Atlassian (Jira)
    "AtlassianTokens",
    "AtlassianResource",
    "AtlassianUserInfo",
    "get_atlassian_client_config",
    "atlassian_exchange_code_for_tokens",
    "atlassian_refresh_access_token",
    "atlassian_is_token_expired",
    "get_atlassian_auth_url",
    "JIRA_WORKFLOW_SCOPES",
    "JIRA_READ_ONLY_SCOPES",
    # Linear
    "LinearTokens",
    "LinearUserInfo",
    "get_linear_client_config",
    "linear_exchange_code_for_tokens",
    "linear_refresh_access_token",
    "linear_is_token_expired",
    "get_linear_auth_url",
    "linear_revoke_token",
    "LINEAR_DEFAULT_SCOPES",
    # GitLab
    "GitLabTokens",
    "GitLabUserInfo",
    "get_gitlab_client_config",
    "gitlab_exchange_code_for_tokens",
    "gitlab_refresh_access_token",
    "gitlab_is_token_expired",
    "get_gitlab_auth_url",
    "GITLAB_DEFAULT_SCOPES",
    # Box
    "BoxTokens",
    "BoxUserInfo",
    "get_box_client_config",
    "box_exchange_code_for_tokens",
    "box_refresh_access_token",
    "box_is_token_expired",
    "get_box_auth_url",
    "BOX_DEFAULT_SCOPES",
    # ClickUp
    "ClickUpTokens",
    "ClickUpUserInfo",
    "get_clickup_client_config",
    "clickup_exchange_code_for_tokens",
    "clickup_refresh_access_token",
    "clickup_is_token_expired",
    "get_clickup_auth_url",
    "CLICKUP_DEFAULT_SCOPES",
    # Asana
    "AsanaTokens",
    "AsanaUserInfo",
    "get_asana_client_config",
    "asana_exchange_code_for_tokens",
    "asana_refresh_access_token",
    "asana_is_token_expired",
    "get_asana_auth_url",
    "ASANA_DEFAULT_SCOPES",
    # Monday
    "MondayTokens",
    "MondayUserInfo",
    "get_monday_client_config",
    "monday_exchange_code_for_tokens",
    "monday_refresh_access_token",
    "monday_is_token_expired",
    "get_monday_auth_url",
    "MONDAY_DEFAULT_SCOPES",
    # Reddit
    "RedditTokens",
    "RedditUserInfo",
    "get_reddit_client_config",
    "reddit_exchange_code_for_tokens",
    "reddit_refresh_access_token",
    "reddit_is_token_expired",
    "get_reddit_auth_url",
    "REDDIT_WORKFLOW_SCOPES",
    # Notion
    "NotionTokens",
    "NotionWorkspaceInfo",
    "get_notion_client_config",
    "notion_exchange_code_for_tokens",
    "notion_refresh_access_token",
    "notion_is_token_expired",
    "get_notion_auth_url",
    # Microsoft
    "MicrosoftTokens",
    "MicrosoftUserInfo",
    "get_microsoft_client_config",
    "microsoft_exchange_code_for_tokens",
    "microsoft_refresh_access_token",
    "microsoft_validate_token",
    "microsoft_is_token_expired",
    "get_microsoft_auth_url",
    "microsoft_revoke_token",
    # Facebook (for Instagram)
    "FacebookTokens",
    "InstagramAccountInfo",
    "get_facebook_client_config",
    "facebook_exchange_code_for_tokens",
    "facebook_refresh_access_token",
    "facebook_validate_token",
    "facebook_is_token_expired",
    "get_facebook_auth_url",
    # Twitter
    "TwitterTokenResponse",
    "TwitterUserInfo",
    "twitter_exchange_code_for_tokens",
    "twitter_refresh_access_token",
    "twitter_is_token_expired",
    "twitter_get_user_info",
    "twitter_revoke_token",
    "twitter_calculate_expires_at",
    # Slack
    "SlackTokens",
    "SlackWorkspaceInfo",
    "get_slack_client_config",
    "slack_exchange_code_for_tokens",
    "slack_refresh_access_token",
    "slack_is_token_expired",
    "get_slack_auth_url",
    "slack_validate_token",
    "SLACK_WORKFLOW_SCOPES",
    "SLACK_READONLY_SCOPES",
    # Typeform
    "TypeformTokens",
    "TypeformUserInfo",
    "get_typeform_client_config",
    "typeform_exchange_code_for_tokens",
    "typeform_refresh_access_token",
    "typeform_is_token_expired",
    "get_typeform_auth_url",
    "TYPEFORM_FULL_SCOPES",
    # WordPress
    "WordPressTokens",
    "WordPressUserInfo",
    "get_wordpress_client_config",
    "wordpress_exchange_code_for_tokens",
    "wordpress_refresh_access_token",
    "wordpress_is_token_expired",
    "get_wordpress_auth_url",
    "WORDPRESS_DEFAULT_SCOPES",
]
