"""
Node output schema tracking + LLM-curated reference suggestions.

One storage table (``workflow_node_output_schemas``), one rule for the
runtime tracker: **fill what is NULL on the row, leave what's populated
alone.** Concretely:

* The output payload becomes a type-descriptor tree (e.g.
  ``{"name": "John"} → {"name": "string"}``) and the row is upserted by
  ``SHA256(node_type, node_operation, schema)`` — equivalent shapes
  dedup globally.
* ``suggested_refs`` is generated by an LLM (gpt-oss-120b via Groq /
  Cerebras through OpenRouter) only when that column is currently NULL.
  A self-hosted installation also needs a non-empty ``OPENROUTER_API_KEY``;
  without one this optional enrichment is skipped without making a request.
  Once set the runtime never overwrites — manual re-curation owns the
  schema-only → sample-based upgrade.
* ``sample_output_clipped`` is filled on every observation where it is
  NULL — including rows that were schema-only prefilled — so a later
  manual re-curation pass has real samples to work from.

The LLM call is awaited inline. Cost is bounded by global dedup: only
the first observation of a given shape pays for the LLM, and rows that
already have everything filled are essentially free (single upsert).
"""

import asyncio
import hashlib
import json
import logging
import os
import re
from typing import Any, Dict, List, Optional

import litellm

from utils.database_pool import get_native_pool
from utils.edition import is_local_edition

# ``all_schema_paths`` is imported lazily inside ``_generate_suggested_refs``
# to avoid a circular import through the workflow package.

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Optional schema-reference enrichment model configuration
# ---------------------------------------------------------------------------

_SUGGESTED_REFS_MODEL = "openrouter/openai/gpt-oss-120b"
_SUGGESTED_REFS_PROVIDER_ORDER = ["groq", "cerebras"]
_SUGGESTED_REFS_TIMEOUT_S = 5.0
_SUGGESTED_REFS_TEMPERATURE = 0.2
_SUGGESTED_REFS_MAX_ATTEMPTS = 3
_SUGGESTED_REFS_MIN = 1
_SUGGESTED_REFS_MAX = 15

_CLIP_STRING_MAX = 80
_CLIP_DEPTH_MAX = 8

_JSON_OBJECT_RE = re.compile(r"\{.*\}", re.DOTALL)


def _configured_openrouter_api_key() -> Optional[str]:
    """Return the explicitly configured server key, ignoring blank values."""
    api_key = os.environ.get("OPENROUTER_API_KEY", "").strip()
    return api_key or None


# ---------------------------------------------------------------------------
# Schema / clip-values extraction
# ---------------------------------------------------------------------------

def infer_type(value: Any) -> str:
    """Infer a simple type descriptor for a value."""
    if value is None:
        return "null"
    elif isinstance(value, bool):
        return "boolean"
    elif isinstance(value, int):
        return "integer"
    elif isinstance(value, float):
        return "float"
    elif isinstance(value, str):
        return "string"
    elif isinstance(value, list):
        return "array"
    elif isinstance(value, dict):
        return "object"
    else:
        return "unknown"


def extract_schema(data: Any, max_depth: int = 10) -> Any:
    """Extract type-only schema from data. See module docstring for examples."""
    if max_depth <= 0:
        return infer_type(data)

    if data is None:
        return "null"

    # bool must come before int (bool is a subclass of int).
    if isinstance(data, bool):
        return "boolean"
    if isinstance(data, int):
        return "integer"
    if isinstance(data, float):
        return "float"
    if isinstance(data, str):
        return "string"

    if isinstance(data, list):
        if len(data) == 0:
            return []
        first_item = None
        for item in data[:10]:
            if item is not None:
                first_item = item
                break
        if first_item is None:
            return ["null"]
        # 2D arrays vary too much to dedup meaningfully.
        if isinstance(first_item, list):
            return [[]]
        if isinstance(first_item, dict):
            merged_schema: Dict[str, Any] = {}
            for item in data[:5]:
                if isinstance(item, dict):
                    for key, value in item.items():
                        if key not in merged_schema:
                            merged_schema[key] = extract_schema(value, max_depth - 1)
            return [merged_schema] if merged_schema else [{}]
        return [extract_schema(first_item, max_depth - 1)]

    if isinstance(data, dict):
        return {key: extract_schema(value, max_depth - 1) for key, value in data.items()}

    return "unknown"


def clip_values(
    data: Any,
    max_string: int = _CLIP_STRING_MAX,
    max_depth: int = _CLIP_DEPTH_MAX,
) -> Any:
    """Build a sample-value tree that mirrors ``extract_schema``'s shape.

    Keeps one truncated value per leaf so the LLM can see what fields
    actually contain (e.g. "permalink looks like a URL", "text contains
    the message body"). Strings clipped to ``max_string`` chars, arrays
    sampled to the first item, depth-bounded.
    """
    if max_depth <= 0:
        return infer_type(data)

    if data is None:
        return None
    if isinstance(data, bool):
        return data
    if isinstance(data, (int, float)):
        return data
    if isinstance(data, str):
        if len(data) <= max_string:
            return data
        return data[:max_string] + "…"

    if isinstance(data, list):
        if not data:
            return []
        for item in data:
            if item is not None:
                return [clip_values(item, max_string, max_depth - 1)]
        return [None]

    if isinstance(data, dict):
        return {k: clip_values(v, max_string, max_depth - 1) for k, v in data.items()}

    return None


def compute_schema_hash(node_type: str, node_operation: str, schema: Any) -> str:
    """Deterministic dedup hash. Sorted keys → stable across dict ordering."""
    combined = json.dumps(
        [node_type, node_operation, schema],
        sort_keys=True,
        separators=(",", ":"),
    )
    return hashlib.sha256(combined.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# Suggested-references generation
# ---------------------------------------------------------------------------

_SUGGESTED_REFS_PROMPT = """You help non-technical users pick which fields from an automation node's output to drag into downstream nodes.

You will see:
- A node type and operation (e.g. automation-slack / read_channel)
- A type-only output schema (field names → types)
- A clipped sample of one real execution showing what values look like

Pick between {min_refs} and {max_refs} fields that are most generally useful for downstream nodes. Prefer:
- Human-meaningful content (text, names, titles, URLs) over internal IDs/flags
- Top-level fields over deeply nested ones unless the nested field is the actual payload
- Fields whose value carries the information someone would want to use, format, or filter on

Each pick must be an exact reference path that exists in the schema. For arrays of objects, use `arrayName[].fieldName`.

Return ONLY a JSON object — no prose, no markdown — with this exact shape:

{{
  "refs": [
    {{
      "path": "exact.path.from.schema",
      "label": "Short human label (2-4 words)",
      "description": "One short sentence on what this contains and when to use it."
    }}
  ]
}}

Order the array from most to least useful."""


def _build_suggested_refs_messages(
    node_type: str,
    node_operation: str,
    schema: Any,
    clipped_sample: Any,
) -> List[Dict[str, Any]]:
    system_prompt = _SUGGESTED_REFS_PROMPT.format(
        min_refs=_SUGGESTED_REFS_MIN,
        max_refs=_SUGGESTED_REFS_MAX,
    )
    user_prompt = (
        f"Node: {node_type}\n"
        f"Operation: {node_operation}\n\n"
        f"Schema (type descriptors):\n{json.dumps(schema, indent=2)}\n\n"
        f"Sample values (clipped):\n{json.dumps(clipped_sample, indent=2, default=str)}"
    )
    return [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]


def _extract_json_object(text: str) -> Optional[Dict[str, Any]]:
    """Best-effort JSON-object extraction from a model response."""
    if not text:
        return None
    try:
        parsed = json.loads(text.strip())
        if isinstance(parsed, dict):
            return parsed
    except json.JSONDecodeError:
        pass
    match = _JSON_OBJECT_RE.search(text)
    if not match:
        return None
    try:
        parsed = json.loads(match.group(0))
        return parsed if isinstance(parsed, dict) else None
    except json.JSONDecodeError:
        return None


def _validate_suggested_refs(
    parsed: Any,
    valid_paths: set,
) -> Optional[List[Dict[str, str]]]:
    """Structural + path-existence validation. Returns the cleaned list or None."""
    if not isinstance(parsed, dict):
        return None
    refs = parsed.get("refs")
    if not isinstance(refs, list):
        return None
    if not (_SUGGESTED_REFS_MIN <= len(refs) <= _SUGGESTED_REFS_MAX):
        return None

    cleaned: List[Dict[str, str]] = []
    seen_paths: set = set()
    for entry in refs:
        if not isinstance(entry, dict):
            return None
        path = entry.get("path")
        label = entry.get("label")
        description = entry.get("description")
        if not isinstance(path, str) or not path.strip():
            return None
        if not isinstance(label, str) or not label.strip():
            return None
        if not isinstance(description, str) or not description.strip():
            return None
        path = path.strip()
        if path in seen_paths:
            return None
        if path not in valid_paths:
            return None
        seen_paths.add(path)
        cleaned.append({
            "path": path,
            "label": label.strip(),
            "description": description.strip(),
        })
    return cleaned


async def _generate_suggested_refs(
    node_type: str,
    node_operation: str,
    schema: Any,
    output: Any,
) -> Optional[List[Dict[str, str]]]:
    """Call the LLM and validate, retrying up to ``_SUGGESTED_REFS_MAX_ATTEMPTS``
    times within a single invocation. Returns None if every attempt fails.

    In the self-hosted edition this is optional enrichment: a missing or blank
    server-side OpenRouter key returns immediately, before LiteLLM can fall back
    to cookie auth or make an unauthenticated outbound request. Hosted keeps its
    existing provider-auth behavior.
    """
    api_key = _configured_openrouter_api_key()
    if is_local_edition() and api_key is None:
        return None

    from coder.workflow.workflow_schema import all_schema_paths

    valid_paths = all_schema_paths(schema)
    if not valid_paths:
        return None

    clipped_sample = clip_values(output)
    messages = _build_suggested_refs_messages(node_type, node_operation, schema, clipped_sample)
    extra_body = {
        "provider": {
            "order": _SUGGESTED_REFS_PROVIDER_ORDER,
            "allow_fallbacks": False,
        },
    }

    last_violation: Optional[str] = None
    for attempt in range(1, _SUGGESTED_REFS_MAX_ATTEMPTS + 1):
        try:
            completion_kwargs: Dict[str, Any] = {
                "model": _SUGGESTED_REFS_MODEL,
                "messages": messages,
                "temperature": _SUGGESTED_REFS_TEMPERATURE,
                "timeout": _SUGGESTED_REFS_TIMEOUT_S,
                "extra_body": extra_body,
            }
            if api_key is not None:
                # Passing the configured key explicitly prevents LiteLLM from
                # selecting some other ambient authentication mechanism.
                completion_kwargs["api_key"] = api_key
            response = await litellm.acompletion(**completion_kwargs)
        except Exception as e:
            last_violation = f"llm_error: {e}"
            logger.info(
                f"[SchemaTracker] Suggested-refs LLM call failed "
                f"({node_type}:{node_operation}, attempt {attempt}): {e}"
            )
            continue

        raw = ""
        try:
            raw = response.choices[0].message.content or ""
        except Exception:
            raw = ""

        parsed = _extract_json_object(raw)
        cleaned = _validate_suggested_refs(parsed, valid_paths)
        if cleaned is not None:
            return cleaned

        last_violation = f"validation_failed: {raw[:200]!r}"
        logger.info(
            f"[SchemaTracker] Suggested-refs validation failed "
            f"({node_type}:{node_operation}, attempt {attempt})"
        )

    logger.warning(
        f"[SchemaTracker] Suggested-refs giving up after {_SUGGESTED_REFS_MAX_ATTEMPTS} attempts "
        f"({node_type}:{node_operation}): {last_violation}"
    )
    return None


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

async def track_node_schema(
    node_type: str,
    node_operation: str,
    output: Any,
    config: Optional[Dict[str, Any]] = None,
) -> None:
    """Record a node's output schema, then fill whichever of
    ``suggested_refs`` / ``sample_output_clipped`` is still NULL on the row.

    Write rule: fill the NULL columns, leave the populated ones alone. The
    runtime tracker never overwrites a value it didn't write — manual
    re-curation is the only path that replaces existing refs.

    The LLM call (for refs) is skipped entirely when refs is already set,
    so prefilled rows only pay for the (tiny) sample write going forward.

    Awaits the upsert + (when needed) the LLM call. All exceptions are
    swallowed; schema tracking must never break workflow execution.
    """
    try:
        schema = extract_schema(output)
        schema_hash = compute_schema_hash(node_type, node_operation, schema)

        safe_config = None
        if config:
            safe_config = {
                k: v for k, v in config.items()
                if k != "credentialIds" and not k.endswith("_secret")
            }

        pool = get_native_pool()

        upsert_query = """
            INSERT INTO workflow_node_output_schemas (
                node_type, node_operation, output_schema, schema_hash, sample_config
            ) VALUES ($1, $2, $3, $4, $5)
            ON CONFLICT (schema_hash) DO UPDATE SET
                last_seen_at = NOW(),
                occurrence_count = workflow_node_output_schemas.occurrence_count + 1
            RETURNING suggested_refs, sample_output_clipped
        """
        # Pass raw Python objects for jsonb params — the asyncpg jsonb codec
        # (setup_asyncpg_codecs) already json.dumps() them on the way in.
        # Pre-serializing here would double-encode, storing a JSON string
        # scalar that reads back as a str instead of a dict/list.
        rows = await pool.fetch(
            upsert_query,
            node_type, node_operation, schema, schema_hash,
            safe_config,
        )
        row = rows[0] if rows else None
        need_refs = row is None or row["suggested_refs"] is None
        need_sample = row is None or row["sample_output_clipped"] is None

        if not need_refs and not need_sample:
            logger.debug(
                f"[SchemaTracker] Both columns set for {node_type}:{node_operation} "
                f"(hash {schema_hash[:8]}…), skipping"
            )
            return

        # Run the LLM only when we actually need refs. clip_values is fast,
        # so we always compute it up front when we need it.
        suggested_refs = None
        if need_refs:
            suggested_refs = await _generate_suggested_refs(
                node_type, node_operation, schema, output,
            )

        # Raw objects, not json.dumps() — the jsonb codec serializes them.
        # None is passed through as SQL NULL (asyncpg skips the codec for None).
        refs_param = suggested_refs
        sample_param = clip_values(output) if need_sample else None

        if refs_param is None and sample_param is None:
            # Nothing to write — needed refs but LLM failed, sample was
            # already populated. Next observation retries refs.
            return

        # One UPDATE, COALESCE-guarded: only NULL columns get filled. If a
        # racing worker populated something between our SELECT and UPDATE,
        # their value wins — we never overwrite a non-NULL value.
        await pool.execute(
            """
            UPDATE workflow_node_output_schemas
            SET suggested_refs = COALESCE(suggested_refs, $1::jsonb),
                sample_output_clipped = COALESCE(sample_output_clipped, $2::jsonb),
                suggestions_updated_at = CASE
                    WHEN suggested_refs IS NULL AND $1::jsonb IS NOT NULL THEN NOW()
                    ELSE suggestions_updated_at
                END
            WHERE schema_hash = $3
            """,
            refs_param,
            sample_param,
            schema_hash,
        )
        logger.debug(
            f"[SchemaTracker] Filled {node_type}:{node_operation} "
            f"(hash {schema_hash[:8]}…): "
            f"refs={'written' if refs_param else 'skipped'}, "
            f"sample={'written' if sample_param else 'skipped'}"
        )
    except asyncio.CancelledError:
        raise
    except Exception as e:
        logger.warning(
            f"[SchemaTracker] Failed to track schema for {node_type}:{node_operation}: {e}"
        )


async def get_schema_for_node(node_type: str, node_operation: str) -> Optional[Dict[str, Any]]:
    """Most-common schema for a (type, operation), or None."""
    try:
        return await get_native_pool().fetchval(
            """
            SELECT output_schema
            FROM workflow_node_output_schemas
            WHERE node_type = $1 AND node_operation = $2
            ORDER BY occurrence_count DESC
            LIMIT 1
            """,
            node_type, node_operation,
        )
    except Exception as e:
        logger.warning(f"[SchemaTracker] Failed to get schema for {node_type}:{node_operation}: {e}")
        return None


async def get_schema_with_suggestions(
    node_type: str,
    node_operation: str,
) -> Optional[Dict[str, Any]]:
    """Most-common schema row with its curated suggestions.

    Returns ``{"schema": ..., "suggested_refs": ... | None}`` or ``None``
    if no row exists yet. ``suggested_refs`` is None while the LLM hasn't
    produced a valid result yet (loading state on the frontend).
    """
    try:
        rows = await get_native_pool().fetch(
            """
            SELECT output_schema, suggested_refs
            FROM workflow_node_output_schemas
            WHERE node_type = $1 AND node_operation = $2
            ORDER BY occurrence_count DESC
            LIMIT 1
            """,
            node_type, node_operation,
        )
        if not rows:
            return None
        row = rows[0]
        return {
            "schema": row["output_schema"],
            "suggested_refs": row["suggested_refs"],
        }
    except Exception as e:
        logger.warning(
            f"[SchemaTracker] Failed to get schema+suggestions for {node_type}:{node_operation}: {e}"
        )
        return None


async def get_all_schemas_for_node(node_type: str, node_operation: str) -> list:
    """All known schemas for a (type, operation), ordered by occurrence count."""
    try:
        rows = await get_native_pool().fetch(
            """
            SELECT output_schema, occurrence_count, first_seen_at, last_seen_at,
                   sample_config, suggested_refs, suggestions_updated_at
            FROM workflow_node_output_schemas
            WHERE node_type = $1 AND node_operation = $2
            ORDER BY occurrence_count DESC
            """,
            node_type, node_operation,
        )
        return [dict(row) for row in rows]
    except Exception as e:
        logger.warning(f"[SchemaTracker] Failed to get schemas for {node_type}:{node_operation}: {e}")
        return []
