// Cloudflare OAuth authorize route.
// Redirects to Cloudflare's consent screen to request user authorization.
// Uses the standard OAuth 2.0 Authorization Code flow.
// Endpoints confirmed via https://dash.cloudflare.com/.well-known/openid-configuration

import { oauthRedirect } from '~/lib/oauthFlow.server';
import { redirect, type LoaderFunctionArgs } from 'react-router';
import crypto from 'crypto';
import { oauthNotConfiguredResponse } from '~/lib/oauthSetupPage.server';
import { applyInstanceOAuthEnv } from '~/lib/instanceOAuth.server';

const CLOUDFLARE_AUTH_URL = 'https://dash.cloudflare.com/oauth2/auth';

// Cloudflare's new OAuth Clients system (Manage Account → OAuth Clients) has TWO
// separate configuration layers:
//   1. Permission groups (resource-level, what you see in the client's UI)
//   2. OAuth scope strings — must ALSO be registered on the client separately
// Sending a scope string that isn't registered on the client — OR that isn't a
// real Cloudflare scope — returns "invalid, unknown, or malformed" / "not allowed
// to request scope 'X'". Sending no scope at all shows 0 permissions on the consent
// screen (Cloudflare won't issue a token for 0 permissions → "authorization failed").
// The authoritative list of valid scope ids is the Cloudflare API itself:
//   GET https://api.cloudflare.com/client/v4/oauth/scopes  (returns each id, e.g.
//   "realtime.read"). Every string below is validated against that list and must
//   also be registered on the client in the Cloudflare dashboard.
export async function loader({ request }: LoaderFunctionArgs) {
    // Self-hosted: an OAuth app saved in Settings shows up as env vars here.
    await applyInstanceOAuthEnv(request, 'cloudflare');
    const clientId = process.env.CLOUDFLARE_CLIENT_ID;
    const redirectUri = process.env.CLOUDFLARE_REDIRECT_URI;

    if (!clientId || !redirectUri) {
        console.error(
            '[cloudflare.authorize] Missing CLOUDFLARE_CLIENT_ID or CLOUDFLARE_REDIRECT_URI env vars'
        );
        return oauthNotConfiguredResponse({
            request,
            provider: 'cloudflare',
            missing: ['CLOUDFLARE_CLIENT_ID', 'CLOUDFLARE_REDIRECT_URI'],
        });
    }

    const state = Buffer.from(
        JSON.stringify({
            nonce: crypto.randomUUID(),
            timestamp: Date.now(),
        })
    ).toString('base64url');

    // Cloudflare's new OAuth Clients system uses dot notation: resource-name.action
    // (NOT the old Wrangler colon format account:read / workers:write).
    // These are the exact scope identifiers from the OAuth client's scope list.
    const scope = [
        // Refresh tokens: the client's "Refresh Token" grant type alone does NOT
        // issue a refresh_token (empirically, connecting with only the resource
        // scopes stored an empty refresh_token) — 'offline_access' must also be
        // requested. It's an OIDC scope (from openid-configuration scopes_supported,
        // not the /oauth/scopes resource catalog); 'openid' specifically is
        // rejected by the client, so do NOT add it. If 'offline_access' is also
        // rejected, it must be allowed on the client before it can be requested.
        'offline_access',
        // Developer Platform
        'agent-memory.write',
        'browser-rendering.read',
        'browser-rendering.write',
        'cf-agents.read',
        'cf-agents.write',
        'cloud-connector.read',
        'cloud-connector.write',
        'cloudchamber.read',
        'cloudchamber.write',
        'constellation.read',
        'constellation.write',
        'd1.read',
        'd1.write',
        'flagship.evaluate',
        'flagship.read',
        'flagship.write',
        'query-cache.read',
        'query-cache.write',
        'mcp-portals.read',
        'mcp-portals.write',
        'page.read',
        'page.write',
        'pipelines.read',
        'pipelines.send',
        'pipelines.write',
        'pubsub.read',
        'pubsub.write',
        'queues.read',
        'queues.write',
        'realtime.admin',
        'secrets-store.read',
        'secrets-store.write',
        'vectorize.read',
        'vectorize.write',
        'workers-ci.read',
        'workers-ci.write',
        'containers.read',
        'containers.write',
        'workers-kv-storage.read',
        'workers-kv-storage.write',
        'workers-observability.read',
        'workers-observability.write',
        'workers-observability-telemetry.write',
        'r2-catalog.read',
        'r2-catalog.write',
        'r2-catalog-sql.read',
        'workers-r2-bucket-item.read',
        'workers-r2-bucket-item.write',
        'workers-r2.read',
        'workers-r2.write',
        'workers-routes.read',
        'workers-routes.write',
        'workers-scripts.read',
        'workers-scripts.write',
        'workers-tail.read',
        // AI & Machine Learning
        'aiaudit.read',
        'aiaudit.write',
        'aig.read',
        'aig.run',
        'aig.write',
        'ai-search.index',
        'ai-search.read',
        'ai-search.run',
        'ai-search.write',
        'agw.read',
        'agw.run',
        'agw.write',
        'rag.read',
        'rag.run',
        'rag.write',
        'firewall-for-ai.read',
        'firewall-for-ai.write',
        'websearch.run',
        'ai.read',
        'ai.write',
        // DNS & Zones
        'account-dns-settings.read',
        'account-dns-settings.write',
        'dns-firewall.read',
        'dns-firewall.write',
        'dns.read',
        'dns.write',
        'dns-view.read',
        'dns-view.write',
        'registrar-domains.admin',
        'registrar-domains.read',
        'registrar-sandbox-domains.admin',
        'registrar-sandbox-domains.read',
        'zone-custom-asset.read',
        'zone-custom-asset.write',
        'zone-dns-settings.read',
        'zone-dns-settings.write',
        'zone.read',
        'zone.write',
        'zone-settings.read',
        'zone-settings.write',
        'zone-versioning.read',
        'zone-versioning.write',
        // App Security
        'fraud-detection-pii.read',
        'account-firewall-access-rules.read',
        'account-firewall-access-rules.write',
        'account-security-center-insights.read',
        'account-security-center-insights.write',
        'account-waf.read',
        'account-waf.write',
        'request-tracer.read',
        'reports-application-security-report.read',
        'bot-management-feedback.read',
        'bot-management-feedback.write',
        'bot-management.read',
        'bot-management.write',
        'cloudforce-one.read',
        'cloudforce-one.write',
        'ddos-botnet-feed.read',
        'ddos-botnet-feed.write',
        'ddos-protection.read',
        'ddos-protection.write',
        'api-gateway.read',
        'api-gateway.write',
        'domain-page.shield',
        'domain-page-shield.read',
        'firewall-services.read',
        'firewall-services.write',
        'fraud-detection.read',
        'fraud-detection.write',
        'fraud-events.write',
        'fraud-feedback.read',
        'fraud-feedback.write',
        'http-applications.read',
        'http-applications.write',
        'http-ddos-managed-ruleset.read',
        'http-ddos-managed-ruleset.write',
        'iot.read',
        'iot.write',
        'l4-ddos-managed-ruleset.read',
        'l4-ddos-managed-ruleset.write',
        'page-rules.read',
        'page-rules.write',
        'page.shield',
        'page-shield.read',
        'precursor.read',
        'precursor.write',
        'sanitize.read',
        'sanitize.write',
        'tag.read',
        'tag.write',
        'trust-and-safety.read',
        'trust-and-safety.write',
        'challenge-widgets.read',
        'challenge-widgets.write',
        'url-scanner.read',
        'url-scanner.write',
        'zaraz.edit',
        'zaraz.read',
        'zaraz.write',
        'zone-security-center-insights.read',
        'zone-security-center-insights.write',
        'zone-waf.read',
        'zone-waf.write',
        // Rules & Configuration
        'account-custom-error-rules.read',
        'account-custom-error-rules.write',
        'account-custom-pages.read',
        'account-custom-pages.write',
        'account-rule-lists.read',
        'account-rule-lists.write',
        'account-rulesets.read',
        'account-rulesets.write',
        'config-settings.read',
        'config-settings.write',
        'custom-errors.read',
        'custom-errors.write',
        'custom-pages.read',
        'custom-pages.write',
        'dynamic-redirect.read',
        'dynamic-redirect.write',
        'managed-headers.read',
        'managed-headers.write',
        'mass-url-redirects.read',
        'mass-url-redirects.write',
        'origin.read',
        'origin.write',
        'response-compression.read',
        'response-compression.write',
        'select-configuration.read',
        'select-configuration.write',
        'snippets.read',
        'snippets.write',
        'transform-rules.read',
        'transform-rules.write',
        'zone-transform-rules.read',
        'zone-transform-rules.write',
        // Cloudflare One / Zero Trust
        'access-app.read',
        'access-app.revoke',
        'access-app.write',
        'access.read',
        'access.revoke',
        'access.write',
        'zone-access.read',
        'zone-access.revoke',
        'zone-access.write',
        'access-audit-log.read',
        'access-custom-page.read',
        'access-custom-page.write',
        'access-device-posture.read',
        'access-device-posture.write',
        'access-group.read',
        'access-group.write',
        'access-idp.read',
        'access-idp.write',
        'access-key.read',
        'access-key.write',
        'access-certificate.read',
        'access-certificate.write',
        'access-org.read',
        'access-org.revoke',
        'access-org.write',
        'access-acct.read',
        'access-acct.revoke',
        'access-acct.write',
        'access-policy.read',
        'access-policy.write',
        'access-policy-test.read',
        'access-policy-test.write',
        'access-population.read',
        'access-population.write',
        'access-saml-certificate.read',
        'access-saml-certificate.write',
        'access-scim-log.read',
        'access-ssh-auditing.read',
        'access-ssh-auditing.write',
        'access-service-token.read',
        'access-service-token.write',
        'access-tag.read',
        'access-tag.write',
        'access-users.read',
        'access-users.write',
        'access-seats.write',
        'casb.read',
        'casb.write',
        'teams-cds-compute-account.read',
        'teams-cds-compute-account.write',
        'teams-dex.read',
        'teams-dex.write',
        'teams-connector-cloudflared.monitoring',
        'teams-connector-cloudflared.read',
        'teams-connector-cloudflared.write',
        'teams-connector-warp.read',
        'teams-connector-warp.write',
        'teams-connectors.read',
        'teams-connectors.write',
        'teams-networks.read',
        'teams-networks.write',
        'argotunnel.read',
        'argotunnel.write',
        'teams-secure.location',
        'dls.read',
        'dls.write',
        'teams.read',
        'teams.report',
        'teams.write',
        'teams-resilience.read',
        'teams-resilience.write',
        'teams-pii.read',
        // Analytics & Logs
        'account-analytics.read',
        'analytics.read',
        'intel.read',
        'intel.write',
        'account-logs.read',
        'account-logs.write',
        'logs.read',
        'logs.write',
        'radar.read',
        // Network Services
        'account-waiting-rooms.read',
        'address-maps.read',
        'address-maps.write',
        'chinanetwork-steering.read',
        'chinanetwork-steering.write',
        'connectivity-directory.admin',
        'connectivity-directory.bind',
        'connectivity-directory.read',
        'healthcheck.read',
        'healthcheck.write',
        'ip-prefix-bgp-on-demand.read',
        'ip-prefix-bgp-on-demand.write',
        'ip-prefix.read',
        'ip-prefix.write',
        'load-balancers-account.read',
        'load-balancers-account.write',
        'load-balancers.read',
        'load-balancers.write',
        'load-balancing-monitors-and-pools.read',
        'load-balancing-monitors-and-pools.write',
        'pcaps-api.read',
        'pcaps-api.write',
        'magic-firewall.read',
        'magic-firewall.write',
        'fbm.admin',
        'fbm.read',
        'fbm.write',
        'magic-transit.read',
        'magic-transit.write',
        'magic-wan.read',
        'magic-wan.write',
        'waiting-rooms.read',
        'waiting-rooms.write',
        'web3-hostnames.read',
        'web3-hostnames.write',
        // Media
        'calls.read',
        'calls.write',
        'images.read',
        'images.write',
        'moq.read',
        'moq.write',
        'stream.read',
        'stream.write',
        // Email & Messaging
        'cloud-email-security.read',
        'cloud-email-security.write',
        'email-routing-address.read',
        'email-routing-address.write',
        'email-routing-rule.read',
        'email-routing-rule.write',
        'email-routing-suppression.read',
        'email-routing-suppression.write',
        'email-security-dmarcreports.read',
        'email-security-dmarcreports.write',
        'email-sending.read',
        'email-sending.write',
        // Cache & Performance
        'account-ssl-and-certificates.read',
        'account-ssl-and-certificates.write',
        'cache.purge',
        'cache-settings.read',
        'cache-settings.write',
        'account-disable-esc.read',
        'account-disable-esc.write',
        'zone-disable-esc.read',
        'zone-disable-esc.write',
        'ssl-and-certificates.read',
        'ssl-and-certificates.write',
        // Account & Billing
        'account-api-gateway.read',
        'account-api-gateway.write',
        'account-custom-asset.read',
        'account-custom-asset.write',
        'account-settings.read',
        'account-settings.write',
        'apps.write',
        'integration.write',
        'memberships.read',
        'memberships.write',
        'notifications.read',
        'notifications.write',
        'scim-provisioning.write',
        'user-details.read',
        'user-details.write',
        // Other
        'artifacts.read',
        'artifacts.write',
        'resource-library.read',
        'resource-library.write',
        'resource-sharing.read',
    ].join(' ');

    const params = new URLSearchParams({
        client_id: clientId,
        redirect_uri: redirectUri,
        response_type: 'code',
        scope,
        state,
    });

    return oauthRedirect(
        request,
        `${CLOUDFLARE_AUTH_URL}?${params.toString()}`
    );
}
