// Shared authentication logic for both page routes and API routes
// Provides a single source of truth for all auth operations

import { createServerSupabaseClient } from '~/lib/supabase';

const PUBLIC_URL = process.env.VITE_PUBLIC_URL || 'http://localhost:5173';
const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY;

// Verify Cloudflare Turnstile CAPTCHA token
async function verifyCaptchaToken(token: string | null): Promise<{ success: boolean; error?: string }> {
  // Deployments with the captcha switched off (self-hosted, single-tenant)
  // have no Turnstile config and no verification edge function to call — the
  // widget never renders, so there is no token to check either.
  if (process.env.VITE_DISABLE_CAPTCHA === 'true') {
    return { success: true };
  }

  if (!token) {
    return { success: false, error: 'CAPTCHA verification required' };
  }

  // Skip verification for test tokens ONLY in development environment
  // Test tokens are generated by Cloudflare's test site key: 1x00000000000000000000AA
  // Security: Using NODE_ENV instead of request.url to prevent X-Forwarded-Host spoofing
  const isDevelopment = process.env.NODE_ENV === 'development';

  if (isDevelopment && (token.includes('DUMMY') || token.startsWith('XXXX.'))) {
    console.log('[CAPTCHA] Skipping verification for test token in development environment');
    return { success: true };
  }

  try {
    console.log('[CAPTCHA] Verifying request');

    const response = await fetch(`${SUPABASE_URL}/functions/v1/cloudflare-turnstile`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${SUPABASE_ANON_KEY}`,
      },
      body: JSON.stringify({ token }),
    });

    console.log('[CAPTCHA] Response status:', response.status);
    const result = await response.json();

    if (!result.success) {
      console.error('[CAPTCHA] Verification failed', {
        errorCodes: result['error-codes'],
      });
      return { success: false, error: 'CAPTCHA verification failed. Please try again.' };
    }

    console.log('[CAPTCHA] Verification successful!');
    return { success: true };
  } catch (error) {
    console.error('[CAPTCHA] Exception during verification:', error);
    return { success: false, error: 'CAPTCHA verification error. Please try again.' };
  }
}

export async function authenticate(request: Request, type: 'login' | 'register' | 'reset' | 'google' | 'sso', data?: any, nextUrl?: string) {
  const headers = new Headers();
  const supabase = createServerSupabaseClient(request, headers);

  // Dynamically determine the redirect URL based on the request origin
  // This ensures we redirect back to the same port the user is using
  const requestUrl = new URL(request.url);
  const origin = requestUrl.origin;

  // Use dynamic origin for localhost and ngrok (dev tunnels), configured URL for production
  const isDevOrigin = origin.includes('localhost') || origin.includes('ngrok') || origin.includes('127.0.0.1');
  const redirectBase = isDevOrigin ? origin : PUBLIC_URL;

  switch (type) {
    case 'login': {
      // Verify CAPTCHA token first
      const captchaResult = await verifyCaptchaToken(data.captchaToken);
      if (!captchaResult.success) {
        return { error: captchaResult.error, headers };
      }

      const { error } = await supabase.auth.signInWithPassword({
        email: data.email,
        password: data.password
      });
      return {
        error: error?.message === 'Invalid login credentials'
          ? 'Invalid email or password. Please try again.'
          : error?.message,
        headers
      };
    }

    case 'register': {
      const { email, password, confirmPassword, username, captchaToken } = data;

      // Verify CAPTCHA token first
      const captchaResult = await verifyCaptchaToken(captchaToken);
      if (!captchaResult.success) {
        return { error: captchaResult.error, headers };
      }

      // Only enforced when the form actually collects a confirmation. Signup
      // asks for one field; surfaces that still ask twice keep the check.
      if (typeof confirmPassword === 'string' && confirmPassword.length > 0
          && password !== confirmPassword) {
        return { error: 'Passwords do not match', headers };
      }

      // Use provided nextUrl or default to /dashboard for post-confirmation redirect.
      // The confirmation template appends &token_hash=...&type=email to this URL
      // ({{ .RedirectTo }} in generate_supabase_email_templates.py), so it must carry
      // a query string. /auth/confirm verifies server-side with no browser-bound
      // state, so the link works even when opened in a different browser or device.
      const callbackNext = nextUrl ? encodeURIComponent(nextUrl) : '%2Fdashboard';
      const { data: signUpData, error } = await supabase.auth.signUp({
        email,
        password,
        options: {
          emailRedirectTo: `${redirectBase}/auth/confirm?next=${callbackNext}`,
          ...(username && { data: { username } })
        }
      });

      // A session on the signUp response means the deployment doesn't require
      // email confirmation (self-hosted default), so the account is already
      // usable and its cookies are on `headers` — land them in the app instead
      // of asking them to check a mailbox that will never receive anything.
      if (!error && signUpData?.session) {
        return { error: undefined, redirectTo: nextUrl || '/dashboard', headers };
      }

      return {
        error: error?.message,
        success: !error && 'Please check your email for a confirmation link to complete your registration.',
        headers
      };
    }

    case 'reset': {
      // The recovery template appends &token_hash=...&type=recovery ({{ .RedirectTo }});
      // /auth/confirm verifies server-side (works cross-browser) and lands on the
      // password form. /auth/reset-password only remains for pre-swap ?code= links.
      const { error } = await supabase.auth.resetPasswordForEmail(data.email, {
        redirectTo: `${redirectBase}/auth/confirm?next=${encodeURIComponent('/auth/update-password')}`,
      });

      return {
        error: error?.message,
        success: !error && 'Password reset link sent! Please check your email.',
        headers
      };
    }

    case 'google': {
      // Use provided nextUrl or default to /dashboard
      const callbackNext = nextUrl ? encodeURIComponent(nextUrl) : '/dashboard';
      const { data: authData, error } = await supabase.auth.signInWithOAuth({
        provider: 'google',
        options: { redirectTo: `${redirectBase}/auth/callback?next=${callbackNext}` }
      });

      return {
        error: error && 'Failed to initialize Google login',
        authUrl: authData?.url,
        headers
      };
    }

    case 'sso': {
      // SSO login via SAML - data.slug is required (organization workspace identifier)
      const slug = data?.slug?.trim().toLowerCase();
      if (!slug) {
        return { error: 'Organization identifier is required for SSO login', headers };
      }

      // Look up organization by slug using RPC function (only exposes necessary fields, not balance/settings)
      const { data: orgs, error: orgError } = await supabase
        .rpc('lookup_sso_organization', { org_slug: slug });

      const org = orgs?.[0];

      if (orgError || !org) {
        return { error: 'Organization not found. Please check the identifier and try again.', headers };
      }

      if (!org.sso_enabled || !org.sso_provider_id) {
        return { error: `SSO is not configured for ${org.name}. Please contact your administrator.`, headers };
      }

      const callbackNext = nextUrl ? encodeURIComponent(nextUrl) : '/dashboard';
      const { data: ssoData, error } = await supabase.auth.signInWithSSO({
        providerId: org.sso_provider_id,
        options: {
          redirectTo: `${redirectBase}/auth/callback?next=${callbackNext}`
        }
      });

      if (error) {
        return { error: error.message || 'Failed to initialize SSO login', headers };
      }

      return {
        ssoUrl: ssoData?.url,
        headers
      };
    }
  }
}