#!/usr/bin/env sh
# Generate this instance's secrets into .env, once.
#
# Every value here is unique to the installation. There are no default
# credentials to forget to change, which is the failure mode that turns a
# self-hosted automation platform — one holding every integration's OAuth
# tokens — into someone else's.
#
# Re-running keeps existing values and only fills in what is missing, so it is
# safe to run after an upgrade adds a new setting.

set -eu

cd "$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)"
ENV_FILE="${NOCLICK_ENV_FILE:-.env}"

command -v openssl >/dev/null 2>&1 || {
    echo "openssl is required to generate secrets" >&2
    exit 1
}

b64url() { openssl base64 -A | tr '+/' '-_' | tr -d '='; }
# Alphanumeric so the value survives every .env, YAML and URL context it lands
# in; over-generates because stripping the non-alphanumerics shortens it.
rand() { openssl rand -base64 "$((${1:-48} * 2))" | tr -d '\n=+/' | cut -c1-"${1:-48}"; }

# HS256 JWT for a PostgREST role. The anon and service keys are not passwords;
# they are tokens the API roles are recognised by, so they are derived from the
# instance's JWT secret rather than generated independently.
sign_jwt() {
    _role="$1"; _secret="$2"; _iat="$(date +%s)"; _exp=$((_iat + 315360000))
    _header='{"alg":"HS256","typ":"JWT"}'
    _payload="{\"role\":\"${_role}\",\"iss\":\"supabase\",\"iat\":${_iat},\"exp\":${_exp}}"
    _signing="$(printf '%s' "$_header" | b64url).$(printf '%s' "$_payload" | b64url)"
    _sig="$(printf '%s' "$_signing" | openssl dgst -sha256 -hmac "$_secret" -binary | b64url)"
    printf '%s.%s' "$_signing" "$_sig"
}

get_existing() {
    [ -f "$ENV_FILE" ] || return 0
    sed -n "s/^$1=//p" "$ENV_FILE" | head -1
}

# Fernet key for credentials at rest: 32 random bytes, base64 with padding.
fernet_key() { openssl rand -base64 32 | tr '+/' '-_'; }

POSTGRES_PASSWORD="$(get_existing POSTGRES_PASSWORD)"
JWT_SECRET="$(get_existing JWT_SECRET)"
ANON_KEY="$(get_existing ANON_KEY)"
SERVICE_ROLE_KEY="$(get_existing SERVICE_ROLE_KEY)"
CREDENTIALS_ENCRYPTION_KEY="$(get_existing CREDENTIALS_ENCRYPTION_KEY)"
WORKFLOW_JWT_SECRET="$(get_existing WORKFLOW_JWT_SECRET)"
CRON_SCHEDULER_SECRET="$(get_existing CRON_SCHEDULER_SECRET)"
SESSION_SECRET="$(get_existing SESSION_SECRET)"
OBJECT_STORAGE_ACCESS_KEY_ID="$(get_existing OBJECT_STORAGE_ACCESS_KEY_ID)"
OBJECT_STORAGE_SECRET_ACCESS_KEY="$(get_existing OBJECT_STORAGE_SECRET_ACCESS_KEY)"

[ -n "$POSTGRES_PASSWORD" ] || POSTGRES_PASSWORD="$(rand 40)"
[ -n "$JWT_SECRET" ] || JWT_SECRET="$(rand 64)"
[ -n "$CREDENTIALS_ENCRYPTION_KEY" ] || CREDENTIALS_ENCRYPTION_KEY="$(fernet_key)"
[ -n "$WORKFLOW_JWT_SECRET" ] || WORKFLOW_JWT_SECRET="$(rand 64)"
[ -n "$CRON_SCHEDULER_SECRET" ] || CRON_SCHEDULER_SECRET="$(rand 64)"
[ -n "$SESSION_SECRET" ] || SESSION_SECRET="$(rand 64)"
[ -n "$OBJECT_STORAGE_ACCESS_KEY_ID" ] || OBJECT_STORAGE_ACCESS_KEY_ID="noclick-$(rand 12)"
[ -n "$OBJECT_STORAGE_SECRET_ACCESS_KEY" ] || OBJECT_STORAGE_SECRET_ACCESS_KEY="$(rand 40)"
# The API keys are only valid for the secret they were signed with.
[ -n "$ANON_KEY" ] || ANON_KEY="$(sign_jwt anon "$JWT_SECRET")"
[ -n "$SERVICE_ROLE_KEY" ] || SERVICE_ROLE_KEY="$(sign_jwt service_role "$JWT_SECRET")"

APP_URL="${NOCLICK_APP_URL:-$(get_existing NOCLICK_APP_URL)}"
API_URL="${NOCLICK_API_URL:-$(get_existing NOCLICK_API_URL)}"
SUPABASE_URL="${NOCLICK_SUPABASE_URL:-$(get_existing NOCLICK_SUPABASE_URL)}"
STORAGE_URL="${NOCLICK_STORAGE_URL:-$(get_existing NOCLICK_STORAGE_URL)}"
RELAY_URL="${NOCLICK_RELAY_URL:-$(get_existing NOCLICK_RELAY_URL)}"
: "${APP_URL:=http://localhost:3000}"
: "${API_URL:=http://api.localhost:8000}"
: "${SUPABASE_URL:=http://supabase.localhost:8001}"
: "${STORAGE_URL:=http://storage.localhost:9000}"
: "${RELAY_URL:=ws://api.localhost:8000/relay}"

umask 077
cat > "$ENV_FILE" <<ENV
# NoClick Community — instance configuration. Generated by scripts/noclick-setup.sh.
#
# SECRETS. Do not commit this file, and back up CREDENTIALS_ENCRYPTION_KEY
# somewhere else: without it every stored integration credential is unreadable.

# ── Public URLs ──────────────────────────────────────────────────────────────
# The browser, the frontend server and the backend all use these exact strings.
# Defaults resolve to this machine both inside and outside Docker. Replace all
# five with real hostnames (https://) to publish the instance, then rebuild:
# the VITE_ values are compiled into the browser bundle.
NOCLICK_APP_URL=$APP_URL
NOCLICK_API_URL=$API_URL
NOCLICK_RELAY_URL=$RELAY_URL
NOCLICK_SUPABASE_URL=$SUPABASE_URL
NOCLICK_STORAGE_URL=$STORAGE_URL

# Published ports on the host.
NOCLICK_APP_PORT=3000
NOCLICK_API_PORT=8000
NOCLICK_SUPABASE_PORT=8001
NOCLICK_STORAGE_PORT=9000

# ── Secrets ──────────────────────────────────────────────────────────────────
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
JWT_SECRET=$JWT_SECRET
ANON_KEY=$ANON_KEY
SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY
CREDENTIALS_ENCRYPTION_KEY=$CREDENTIALS_ENCRYPTION_KEY
WORKFLOW_JWT_SECRET=$WORKFLOW_JWT_SECRET
CRON_SCHEDULER_SECRET=$CRON_SCHEDULER_SECRET
SESSION_SECRET=$SESSION_SECRET
OBJECT_STORAGE_ACCESS_KEY_ID=$OBJECT_STORAGE_ACCESS_KEY_ID
OBJECT_STORAGE_SECRET_ACCESS_KEY=$OBJECT_STORAGE_SECRET_ACCESS_KEY

# ── Optional ─────────────────────────────────────────────────────────────────
# Accounts are confirmed without email until an SMTP server is configured.
# Set these together, then set NOCLICK_AUTOCONFIRM_EMAIL=false.
SMTP_HOST=
SMTP_PORT=
SMTP_USERNAME=
SMTP_PASSWORD=
FROM_EMAIL=
NOCLICK_AUTOCONFIRM_EMAIL=true

# NoClick notifications use Resend (separate from GoTrue's SMTP transport).
# Set both together; startup refuses a key without a verified sender identity.
RESEND_API_KEY=
INVITE_FROM_EMAIL=

# Inbound workflow addresses and agent email replies stay hidden until you own
# a domain whose provider forwards mail to this instance's /email/inbound route.
INBOUND_EMAIL_DOMAIN=
EMAIL_RELAY_SECRET=

# Close registration once the accounts you want exist.
NOCLICK_DISABLE_SIGNUP=false

# Instance-wide model keys. Users can bring their own through the credential UI
# instead; these are a convenience, not a requirement. OPENROUTER_API_KEY also
# enables output-field suggestions, which send a clipped node-output sample to
# OpenRouter; see docs/self-hosting.md.
OPENAI_API_KEY=
OPENROUTER_API_KEY=
GEMINI_API_KEY=

# The redis profile runs Valkey (Redis-protocol compatible). Start it with
# docker compose --profile redis up -d; this remains a standard Redis URL.
REDIS_URL=
POSTHOG_API_KEY=
HONEYCOMB_API_KEY=
# Leave unset unless this trusted installation intentionally connects to LAN services.
OUTBOUND_ALLOW_PRIVATE_IPS=
# Deprecated compatibility alias for OUTBOUND_ALLOW_PRIVATE_IPS.
HTTP_NODE_ALLOW_PRIVATE_IPS=
GEOIP_LOOKUP_URL=
# External gateway required only for QR-linked personal WhatsApp accounts.
WAHOOKS_API_KEY=
ENV

printf '%s\n' "Wrote $ENV_FILE"
printf '%s\n' "  app       $APP_URL"
printf '%s\n' "  backend   $API_URL"
# The frontend's production bundle is the memory high-water mark of the whole
# build — it asks Node for a 4 GiB heap, and Docker has to have room for that on
# top of everything already running. Short of it, the build dies after twenty
# minutes with "ResourceExhausted: cannot allocate memory", which says nothing
# about what to change. A warning, not a refusal: this is a heuristic, and a
# machine that disagrees with it should be allowed to try.
docker_mem=$(docker info --format '{{.MemTotal}}' 2>/dev/null || echo 0)
if [ "$docker_mem" -gt 0 ] && [ "$docker_mem" -lt 8589934592 ]; then
    printf '%s\n' ""
    printf '%s\n' "  Warning: Docker is limited to $((docker_mem / 1073741824)) GiB, and the frontend build"
    printf '%s\n' "  asks Node alone for 4 GiB. Anything already running counts against"
    printf '%s\n' "  the same limit, so 8 GiB is the point below which this usually"
    printf '%s\n' "  fails. If the build stops at 'cannot allocate memory', that is"
    printf '%s\n' "  what happened: raise Docker's memory limit and run it again."
fi

printf '%s\n' "Next: docker compose up -d"
