// Schema-based operation helpers used to label and enumerate the discriminator
// options on a node type. Used by NodeConfig's operation picker and the
// Setup surfaces so both render the same human-friendly labels.

import { getSchemaInfo } from './schemaFieldExtractor';

export interface OperationOption {
    value: string;
    label: string;
}

/** Minimal slice of `SchemaInfo` needed to label a discriminator option. */
/** The slice of a JSON-schema option this module reads. Narrower than the
 *  schema itself on purpose: it names exactly what a label can be built from,
 *  so a caller passing the wrong shape fails here rather than producing
 *  "Option 3" at runtime. */
interface SchemaOption {
    $ref?: string;
    title?: string;
    description?: string;
    properties?: Record<
        string,
        { title?: string; 'x-display-name'?: string } | undefined
    >;
}

export interface OptionLabelSource {
    options: readonly SchemaOption[];
    discriminator: {
        fieldName: string | null;
        optionToValue: Map<number, string>;
    };
    resolveRef: (ref: string) => SchemaOption | undefined;
}

/**
 * Extract a clean label from a schema option title.
 * Removes "Config" suffix, common node-type prefixes, and adds spaces before capitals.
 */
export function cleanOperationLabel(title: string): string {
    // Already has spaces — assume it's properly formatted.
    if (title.includes(' ')) return title;
    let label = title.replace(/Config$/, '');
    label = label.replace(
        /^(GoogleCalendar|GoogleSheets|GoogleDrive|GithubRest|Github|Gmail|Airtable|Linear|Telegram|Reddit|Salesforce|YouTube|LinkedIn|HttpRequest|HN|Slack|Discord|Notion|Outlook|HubSpot|Jira)/,
        ''
    );
    return label.replace(/([A-Z])/g, ' $1').trim();
}

function toAutoGeneratedFieldTitle(fieldName: string): string {
    return fieldName
        .split(/[_-]+/)
        .filter(Boolean)
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join(' ');
}

/**
 * Human label for a single discriminator option. Single source of truth shared
 * by NodeConfig's picker and the Setup surfaces so both show the
 * same names. Priority:
 *
 *   1. `x-display-name` stamped on the discriminator field by the backend
 *      rename refactor (e.g. "Send Message to Chat") — always wins when set.
 *   2. The discriminator field's `title`, but only if it's not just the
 *      auto-generated capitalization of the field name (e.g. "Operation").
 *   3. The resolved option's `title`, passed through `cleanOperationLabel`
 *      (strips Config suffix, common node-type prefixes, and adds spaces).
 *   4. First sentence of the option's `description`.
 *   5. Fallback to the discriminator value, capitalized
 *      (e.g. "read_spreadsheet" → "Read Spreadsheet").
 */
export function getOptionDisplayName(
    source: OptionLabelSource,
    optionIndex: number
): string {
    const { options, discriminator, resolveRef } = source;
    const option = options[optionIndex];
    if (!option) return `Option ${optionIndex + 1}`;
    const resolved = option.$ref ? resolveRef(option.$ref) : option;
    const discriminatorValue = discriminator.optionToValue.get(optionIndex);

    if (discriminator.fieldName) {
        const discProp = resolved?.properties?.[discriminator.fieldName];
        const displayName = discProp?.['x-display-name'];
        if (displayName) return displayName;
        if (discProp?.title) {
            const autoGeneratedTitle = toAutoGeneratedFieldTitle(
                discriminator.fieldName
            );
            if (discProp.title !== autoGeneratedTitle) return discProp.title;
        }
    }
    if (resolved?.title) return cleanOperationLabel(resolved.title);
    if (resolved?.description) return resolved.description.split('.')[0];
    if (discriminatorValue) {
        return discriminatorValue
            .replace(/_/g, ' ')
            .replace(/\b\w/g, (c) => c.toUpperCase());
    }
    return `Option ${optionIndex + 1}`;
}

/**
 * Extract the discriminator-driven list of operations for a node type.
 * Returns [] when the node has no discriminator (single config shape).
 */
export function getAvailableOperations(nodeType: string): OperationOption[] {
    const schemaInfo = getSchemaInfo(nodeType);
    if (!schemaInfo || !schemaInfo.hasDiscriminator) return [];

    const operations: OperationOption[] = [];
    for (let i = 0; i < schemaInfo.options.length; i++) {
        const value = schemaInfo.discriminator.optionToValue.get(i);
        if (!value) continue;
        operations.push({ value, label: getOptionDisplayName(schemaInfo, i) });
    }
    return operations;
}

/** Get the discriminator field name for a node type (typically `operation`). */
export function getDiscriminatorFieldName(nodeType: string): string | null {
    const schemaInfo = getSchemaInfo(nodeType);
    return schemaInfo?.discriminator.fieldName ?? null;
}

/** Human-readable label for a given operation value on a node type. */
export function getOperationLabel(
    nodeType: string,
    operationValue?: string
): string {
    if (!operationValue) return 'Not selected';
    const operations = getAvailableOperations(nodeType);
    const op = operations.find((o) => o.value === operationValue);
    return (
        op?.label ||
        operationValue
            .replace(/_/g, ' ')
            .replace(/\b\w/g, (c: string) => c.toUpperCase())
    );
}

// ── Per-option metadata for the OperationPicker ─────────────────────────────
// The picker needs a handful of accessors over the discriminator options
// (category, trigger flag, tier badge, search keywords, description). They are
// pure functions of the node type's schema, so they live here rather than being
// re-derived by each host — the Run popup renders the same picker as the config
// panel and must group, badge and search identically.

type SchemaObject = Record<string, unknown>;

function asObject(value: unknown): SchemaObject | null {
    return value && typeof value === 'object' ? (value as SchemaObject) : null;
}

function resolvedOption(
    nodeType: string,
    optionIndex: number
): SchemaObject | null {
    const schemaInfo = getSchemaInfo(nodeType);
    if (!schemaInfo) return null;
    const option = asObject(schemaInfo.options[optionIndex]);
    const ref = option?.$ref;
    return typeof ref === 'string'
        ? asObject(schemaInfo.resolveRef(ref))
        : option;
}

/** Field carrying the per-operation `x-` annotations, if the schema has one. */
function discriminatorProp(
    nodeType: string,
    optionIndex: number
): SchemaObject | null {
    const schemaInfo = getSchemaInfo(nodeType);
    const field = schemaInfo?.discriminator.fieldName;
    if (!field) return null;
    const props = asObject(resolvedOption(nodeType, optionIndex)?.properties);
    return asObject(props?.[field]);
}

/** Object an operation acts on ("Message", "Channel") — the picker's grouping. */
export function getOperationCategory(
    nodeType: string,
    optionIndex: number
): string | null {
    // Stamped on the discriminator field by the op-rename refactor; the
    // top-level form is the legacy location for nodes not yet migrated.
    const fromField = discriminatorProp(nodeType, optionIndex)?.['x-category'];
    if (typeof fromField === 'string') return fromField;
    const legacy = resolvedOption(nodeType, optionIndex)?.['x-category'];
    return typeof legacy === 'string' ? legacy : null;
}

/** True when this operation starts a workflow on an external event. */
export function getOperationIsTrigger(
    nodeType: string,
    optionIndex: number
): boolean {
    return Boolean(discriminatorProp(nodeType, optionIndex)?.['x-is-trigger']);
}

/** API-tier badge (e.g. Twitter Basic/Pro), when the operation requires one. */
export function getOperationTierLabel(
    nodeType: string,
    optionIndex: number
): string | null {
    const label = resolvedOption(nodeType, optionIndex)?.['x-tier-label'];
    return typeof label === 'string' ? label : null;
}

export function getOperationDescription(
    nodeType: string,
    optionIndex: number
): string | null {
    const fromField = discriminatorProp(nodeType, optionIndex)?.description;
    if (typeof fromField === 'string') return fromField;
    const fromOption = resolvedOption(nodeType, optionIndex)?.description;
    return typeof fromOption === 'string' ? fromOption : null;
}

/** Extra identity text the picker fuzzy-matches beside the label: the raw
 *  discriminator value ("send_message" → "send message"), the option title, and
 *  any `x-keywords` intent synonyms. */
export function getOperationKeywords(
    nodeType: string,
    optionIndex: number
): string {
    const schemaInfo = getSchemaInfo(nodeType);
    const resolved = resolvedOption(nodeType, optionIndex);
    const parts: string[] = [];
    const value = schemaInfo?.discriminator.optionToValue.get(optionIndex);
    if (value) parts.push(value.replace(/[_-]+/g, ' '));
    if (typeof resolved?.title === 'string') parts.push(resolved.title);
    const keywords = discriminatorProp(nodeType, optionIndex)?.['x-keywords'];
    if (Array.isArray(keywords)) parts.push(...keywords.map(String));
    else if (typeof keywords === 'string') parts.push(keywords);
    return parts.join(' ');
}
