"""ClickUp operation → OAuth scope requirements.

ClickUp has no OAuth scopes. Its authorization URL takes only ``client_id``,
``redirect_uri`` and an optional ``state``; there is no ``scope`` parameter and
the docs define no scope vocabulary. What the user picks at consent is which
*Workspaces* to authorize — the token then carries that user's full permissions
inside them. That is why the node's ``x-oauth-scopes`` is empty and must stay
empty: sending a ``scope`` ClickUp does not define changes nothing.

The Personal API Token credential is the same story with no consent step at all.

Two things that look like scopes but are not, so they get no entry here:

- **Plan entitlements.** Guests, workspace user management and Audit Logs are
  Enterprise-plan features. A token on a lower plan is rejected by the API for
  lack of a plan, not for lack of a scope — no grant can fix it.
- **Role permissions.** ClickUp evaluates the authorizing user's own role per
  request, so the same token succeeds or fails depending on who connected it.

Every operation therefore requires authentication and nothing more, which is
what an empty ``scopes`` tuple means. The table is still exhaustive: it exists
so a newly added ClickUp operation cannot slip in without someone re-checking
that ClickUp still has no scopes.
"""

from __future__ import annotations

from nodes.core.oauth_scopes import ScopeRegistry, ScopeRequirement

#: ClickUp defines no scope strings; access comes from the authorized
#: Workspaces, the workspace plan and the connecting user's role.
_NO_SCOPE = ScopeRequirement()

_OPERATIONS: tuple[str, ...] = (
    "add_dependency",
    "add_guest_to_folder",
    "add_guest_to_list",
    "add_guest_to_task",
    "add_tag_to_task",
    "add_tags_from_time_entries",
    "add_task_link",
    "add_task_to_list",
    "change_tag_names_from_time_entries",
    "create_audit_logs",
    "create_chat_channel",
    "create_chat_direct_message_channel",
    "create_chat_location_channel",
    "create_chat_message",
    "create_chat_reaction",
    "create_chat_reply",
    "create_chat_view_comment",
    "create_checklist",
    "create_checklist_item",
    "create_doc",
    "create_folder",
    "create_folder_from_template",
    "create_folder_view",
    "create_folderless_list",
    "create_folderless_list_from_template",
    "create_goal",
    "create_key_result",
    "create_list",
    "create_list_comment",
    "create_list_from_template_in_folder",
    "create_list_view",
    "create_page",
    "create_space",
    "create_space_tag",
    "create_space_view",
    "create_task",
    "create_task_attachment",
    "create_task_comment",
    "create_task_from_template",
    "create_team_view",
    "create_threaded_comment",
    "create_time_entry",
    "create_user_group",
    "create_webhook",
    "custom_request",
    "delete_chat_message",
    "delete_chat_reaction",
    "delete_checklist",
    "delete_checklist_item",
    "delete_comment",
    "delete_dependency",
    "delete_folder",
    "delete_goal",
    "delete_key_result",
    "delete_list",
    "delete_space",
    "delete_space_tag",
    "delete_task",
    "delete_task_link",
    "delete_time_entry",
    "delete_time_tracked",
    "delete_user_group",
    "delete_view",
    "delete_webhook",
    "edit_checklist",
    "edit_checklist_item",
    "edit_guest_on_workspace",
    "edit_key_result",
    "edit_page",
    "edit_space_tag",
    "edit_time_tracked",
    "edit_user_on_workspace",
    "get_accessible_fields",
    "get_all_tags_from_time_entries",
    "get_authorized_user",
    "get_bulk_tasks_time_in_status",
    "get_chat_channel",
    "get_chat_channel_followers",
    "get_chat_channel_members",
    "get_chat_message_reactions",
    "get_chat_message_tagged_users",
    "get_chat_replies",
    "get_chat_view_comments",
    "get_custom_roles",
    "get_doc",
    "get_doc_page_listing",
    "get_doc_pages",
    "get_filtered_team_tasks",
    "get_folder",
    "get_folder_views",
    "get_folderless_lists",
    "get_folders",
    "get_goal",
    "get_goals",
    "get_guest",
    "get_list",
    "get_list_comments",
    "get_list_members",
    "get_list_views",
    "get_lists",
    "get_page",
    "get_running_time_entry",
    "get_shared_hierarchy",
    "get_singular_time_entry",
    "get_space",
    "get_space_tags",
    "get_space_views",
    "get_spaces",
    "get_task",
    "get_task_comments",
    "get_task_members",
    "get_task_time_in_status",
    "get_tasks",
    "get_team_custom_fields",
    "get_team_views",
    "get_teams",
    "get_threaded_comments",
    "get_time_entries",
    "get_time_entry_history",
    "get_tracked_time",
    "get_user",
    "get_user_groups",
    "get_view",
    "get_view_tasks",
    "get_webhooks",
    "get_workspace_members",
    "get_workspace_plan",
    "get_workspace_seats",
    "invite_guest_to_workspace",
    "invite_user_to_workspace",
    "list_chat_channels",
    "list_chat_messages",
    "merge_tasks",
    "on_task_event",
    "remove_custom_field_value",
    "remove_guest_from_folder",
    "remove_guest_from_list",
    "remove_guest_from_task",
    "remove_guest_from_workspace",
    "remove_tag_from_task",
    "remove_tags_from_time_entries",
    "remove_task_from_list",
    "remove_user_from_workspace",
    "search_docs",
    "set_custom_field",
    "start_timer",
    "stop_timer",
    "track_time",
    "update_chat_channel",
    "update_chat_message",
    "update_comment",
    "update_folder",
    "update_goal",
    "update_list",
    "update_space",
    "update_task",
    "update_time_entry",
    "update_user_group",
    "update_view",
    "update_webhook",
)


CLICKUP_SCOPES = ScopeRegistry(
    provider="clickup",
    requirements={operation: _NO_SCOPE for operation in _OPERATIONS},
)
